name: todos_repository_local_storage
description: An app-agnostic data source that can be used by all implementations

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  todos_repository_core:
    path: ../todos_repository_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: null
  test: null
